version: '3'
services:
  app:
    container_name: project-management
    image: project-management:v1
    build: .
    ports:
      - '3003:3000'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - user_network
    volumes:
      - ./config:/app/config

  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: project-management-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@456aA
    ports:
      - '5436:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - user_network

volumes:
  db:

networks:
  user_network:
    name: user_network
    driver: bridge
