node_env: local
server:
  host: 127.0.0.1
  hostname: 127.0.0.1:3000
  swaggerSchema: http
  port: 3000

service:
  baseUrl: api
  baseApi: api
  docsBaseUrl: api/docs
  apiVersion: 1.0

db:
  host: localhost
  # host: db
  port: 5432
  username: postgres
  password: 123@456aA
  name: project-management-dev

jwt:
  secret: superjwts3cr3tkEy
  expTime: 86400

admin:
  username: admin
  password: P@ssW0rD@1

mail:
  host: smtp.gmail.com
  user: your_email
  password: your_email_password
  from: your_email
  port: 587
